source 'https://github.com/CocoaPods/Specs.git'


project 'LazyLibs'

platform :ios, '8.0'

plugin 'cocoapods-amimono'

use_frameworks!

target :LazyLibs do
    pod 'AlamofireObjectMapper'
    pod 'AlamofireImage'
    pod 'FacebookLogin'
    pod 'ObjectMapper'
    pod 'PhoneNumberKit'
    pod 'UIImageEffects'
    pod 'pop'
    pod 'KissXML'
    pod 'MTDates'
    pod 'Punycode-Cocoa'
end

target :LazySpeechKit do
    pod 'YandexSpeechKit'
end

target :LazyMapKit do
    pod 'YandexMapKit'
end

post_install do |installer|
  require 'cocoapods-amimono/patcher'
  Amimono::Patcher.patch!(installer)
end
