source 'https://github.com/CocoaPods/Specs.git'

plugin 'cocoapods-amimono'

project 'StaticPods'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target :StaticPods do
    pod 'AlamofireObjectMapper', '~> 4.0'
    pod 'AlamofireImage'
    pod 'Crashlytics'
    pod 'FacebookLogin'
    #pod 'Mapbox-iOS-SDK'
    pod 'ObjectMapper'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'PhoneNumberKit'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'UIImageEffects'
end


post_install do |installer|
  require 'cocoapods-amimono/patcher'
  Amimono::Patcher.patch!(installer)
end
